### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by victorcastro89** [dfinity/awesome-internet-computer#27]
There are some Broken links in this repository, some examples:

✓ [Internet Computer Tools](https://bmht6-iiaaa-aaaad-qabeq-cai.raw.ic0.app/)

[DFinance](https://dfinance.ai/) - DFinance is building basic DeFi components for the Internet Computer, including: token standard, DEX, stablecoin and lending platform.

**Comment by domwoe** [comment]
Thanks for reporting. This repo has not got any love for quite some time. We'll change that and we'll be happy to receive issues and PRs.

**Comment by Acetarax** [comment]
> There are some Broken links in this repository, some examples:
> 
> ✓ [Internet Computer Tools](https://bmht6-iiaaa-aaaad-qabeq-cai.raw.ic0.app/)
> 
> [DFinance](https://dfinance.ai/) - DFinance is building basic DeFi components for the Internet Computer, including: token standard, DEX, stablecoin and lending platform.
Make use of this https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by rvanasa** [comment]
Fixed in #34
