### ISSUE TITLE
Listing on the awesome list of awesome lists

### ISSUE THREAD

**Issue by nathanosdev** [dfinity/awesome-internet-computer#31]
This list would fit right in here: https://github.com/sindresorhus/awesome#decentralized-systems
I'm happy to open a PR over there if there's agreement.

**Comment by domwoe** [comment]
Hey @nathanosdev ,

seems like a good idea, but we should postpone this a bit for two reasons:
1) The content is pretty dated 
2) We need to think about renaming/rebranding to awesome-ic / awesome-internet-computer. (Herbert curates https://github.com/zire/awesome-IC but we have much more watchers/starts here)

**Comment by nathanosdev** [comment]
Makes sense, thanks! Would you like to keep this ticket open for the future then or close it?

**Comment by domwoe** [comment]
Let's keep this open. We shouldn't forget this.

**Comment by domwoe** [comment]
@nathanosdev Please go ahead! :)

**Comment by nathanosdev** [comment]
Thanks @domwoe. I read their contribution guidelines and it turns out there's a bit more work to do to make sure that my PR over there is accepted, I've prepared a PR with most of the necessary changes: https://github.com/dfinity/awesome-icp/pull/32. I'm happy to discuss alternatives to any changes that I made there, but I made what I felt was the most obvious change to me (like the license for example) to begin with so we have something to work from.

2 action items that cannot be covered in the PR that I could use your help with are:
- renaming the primary branch to `main` instead of `master`
- adding `awesome-list` & `awesome` to the GitHub topics.

**Comment by domwoe** [comment]
Thanks a lot! Should be good to go now

**Comment by nathanosdev** [comment]
PR has been opened here: https://github.com/sindresorhus/awesome/pull/2390

Fingers crossed 🤞

**Comment by rvanasa** [comment]
Updated PR:
- https://github.com/sindresorhus/awesome/pull/2525

**Comment by nathanosdev** [comment]
Thanks for taking this up @rvanasa!

**Comment by nathanosdev** [comment]
So have we thrown in the towel on this one? Shall we close this ticket?

**Comment by domwoe** [comment]
@nathanosdev Yes. I've asked @rvanasa for feedback before and we think it's better to provide a useful list of resources than to strictly adhere to some arbitrary rules.

**Comment by nathanosdev** [comment]
Agreed. At least we did make some improvements along the way so it wasn't a _total_ waste of time :D
